services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: chat_db
      POSTGRES_USER: chat_user
      POSTGRES_PASSWORD: chat_pass
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  auth-service:
    build: ./backend/auth-service
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/chat_db
      SPRING_DATASOURCE_USERNAME: chat_user
      SPRING_DATASOURCE_PASSWORD: chat_pass
    depends_on:
      - postgres

  chat-service:
    build: ./backend/chat-service
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/chat_db
      SPRING_DATASOURCE_USERNAME: chat_user
      SPRING_DATASOURCE_PASSWORD: chat_pass
    depends_on:
      postgres:
      condition: service_healthy